apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -staging
resources:
- ../base
images:
- name: zeus-hello
  newName: zeus-hello
  newTag: c22892049c4de09378db84a0f7fdf524656d38d6
