apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -staging
resources:
- ../base
images:
- name: zeus-hello
  newName: 821405583049.dkr.ecr.eu-central-1.amazonaws.com/zeus-hello
  newTag: 873bacc7faf614fbc4f9b619aea220934c3f31d3
